package View;
import Controller.GestoreMonteore;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private GestoreMonteore controller;
    
    public MainFrame(GestoreMonteore controller) {
        this.controller = controller;
        initComponents();
        fileOpen.addActionListener(this::openFile);
        // da fare fileSave.addActionListener(this::openFile);
        editInsert.addActionListener(this::insertInfo);
        editEdit.addActionListener(this::modificaInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // METODI DI FILE
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileOpen = new javax.swing.JMenuItem();
        fileSave = new javax.swing.JMenuItem();
        fleExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        editInsert = new javax.swing.JMenuItem();
        editEdit = new javax.swing.JMenuItem();
        editView = new javax.swing.JMenuItem();
        editDelete = new javax.swing.JMenuItem();
        menuStatistics = new javax.swing.JMenu();
        statisticsStudentsx = new javax.swing.JMenuItem();
        statisticsRanking = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        infoAbout = new javax.swing.JMenuItem();
        infoCredits = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Last name");

        jLabel2.setText("Activity");

        jButton1.setText("Search");

        jButton2.setText("Reset");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last name", "Section", "Turn", "Activity", "Registered"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Number of students registered:");

        menuFile.setText("File");

        fileOpen.setText("Open");
        menuFile.add(fileOpen);

        fileSave.setText("Save with name");
        menuFile.add(fileSave);

        fleExit.setText("Exit");
        menuFile.add(fleExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        editInsert.setText("Insert");
        menuEdit.add(editInsert);

        editEdit.setText("Edit");
        menuEdit.add(editEdit);

        editView.setText("View list");
        menuEdit.add(editView);

        editDelete.setText("Delete");
        menuEdit.add(editDelete);

        jMenuBar1.add(menuEdit);

        menuStatistics.setText("Statistics");

        statisticsStudentsx.setText("Students per activity");
        menuStatistics.add(statisticsStudentsx);

        statisticsRanking.setText("Activity ranking");
        menuStatistics.add(statisticsRanking);

        jMenuBar1.add(menuStatistics);

        menuInfo.setText("Info");

        infoAbout.setText("About");
        menuInfo.add(infoAbout);

        infoCredits.setText("Credits");
        menuInfo.add(infoCredits);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void openFile (java.awt.event.ActionEvent evt) {                                         
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filtro =
        new FileNameExtensionFilter("File CSV (*.csv)", "csv");
        chooser.setFileFilter(filtro);
        int scelta = chooser.showOpenDialog(this);
        if (scelta == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (!file.getName().toLowerCase().endsWith(".csv")) {
                JOptionPane.showMessageDialog(
                        this,
                        "Seleziona un file CSV!",
                        "Errore",
                        JOptionPane.ERROR_MESSAGE
                );
                return; // interrompe tutto
            }
            
            try {
                controller.apriFile(file);
                JOptionPane.showMessageDialog(
                        this,
                        "File caricato correttamente!"
                );

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                        this,
                        ex.getMessage(),
                        "Errore",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }   
    
    
    // DA FARE SALVA CON NOME E ESCI DAL FILE
    private void saveFile(java.awt.event.ActionEvent evt) {                                         
        System.out.println("SONO QUI");
    }   
    
    
    // METODI DI EDIT
    private void insertInfo(java.awt.event.ActionEvent evt) {
        //n da chiedere
        dialogoInserimentoUtente dialog = new dialogoInserimentoUtente(this, true, controller);
        dialog.setVisible(true);
    } 
    
    
    
    private void modificaInfo(java.awt.event.ActionEvent evt) {                                         
        //dialogoModificaRiga dialog = new dialogoModificaRiga(this, true, controller);
        //dialog.setVisible(true);
    }      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editDelete;
    private javax.swing.JMenuItem editEdit;
    private javax.swing.JMenuItem editInsert;
    private javax.swing.JMenuItem editView;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JMenuItem fleExit;
    private javax.swing.JMenuItem infoAbout;
    private javax.swing.JMenuItem infoCredits;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuStatistics;
    private javax.swing.JMenuItem statisticsRanking;
    private javax.swing.JMenuItem statisticsStudentsx;
    // End of variables declaration//GEN-END:variables
}
